### ISSUE TITLE
Font color is not taken into account

### ISSUE THREAD

**Issue by EtienneAb3d** [blackears/svgSalamander#71] opened 2020-12-10 10:33 UTC
Hi all!

Yesterday, I just did a test to include svgSalamander to read SVG input files in my 3D-stereo freeware:
http://3denlive.com/en.php

When using this `Gnome_All.svg` file with a dark-pink text (see in this ZIP file, github is refusing direct SVG upload):
http://3denlive.com/demos/DemoSVG.zip
![image](https://user-images.githubusercontent.com/25932245/101760300-fb665000-3ada-11eb-8b40-56adefae04c5.png)

I get a rendered black text:
![image](https://user-images.githubusercontent.com/25932245/101760163-cd810b80-3ada-11eb-8b65-f0be9d0305e9.png)

Thanks for your work!

Etienne

**Comment by blackears** [comment] 2020-12-14 01:57
The problem is that Tspan has not been implemented properly.  It may take some time for me to fix this.  In the mean time, you can place your attributes in the Text tag and it should work.

**Comment by EtienneAb3d** [comment] 2020-12-14 11:36
My tool is supposed to be used by people not being technically capable to edit their SVG files. 
I will wait for your improvement.
:)

**Comment by bradh** [comment] 2022-09-24 11:01
Is this resolved by #79?

**Comment by blackears** [comment] 2022-09-25 15:26
I believe it is.  Please open a new issue if you run into any problems with the new implementation.

**Closed by blackears** 2022-09-25 15:26 UTC
